server:
  port: 8088
  servlet:
    context-path: /xhj
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 10000000

spring:
  profiles:
    active: dev
  banner:
    location: ["classpath:banner.txt", "file:./banner.txt"]
  freemarker:
    checkTemplateLocation: false
    template-loader-path: classpath:/templates/
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    time-zone: GMT+8

logging:
  level:
    ciih:
      dsg:
        xhj:
          mapper: debug

swagger:
  version: 1.0
  terms-of-service-url: http://localhost:8080/
  base-package: ciih.dsg.xhj.controller
  contact:
    name: xhj
    url: http://localhost:8080/
    email: 996188227@qq.com