datasource_driver: com.p6spy.engine.spy.P6SpyDriver
datasource_url: jdbc:p6spy:mysql://localhost:3306/ddmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
datasource_username: root
datasource_password: 123456

#datasource_driver: com.mysql.cj.jdbc.Driver
#datasource_url: jdbc:mysql://mysql:3306/ddmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
#datasource_username: root
#datasource_password: ADMIN@zjjy321